In [15]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import time
import scipy.stats as st
from scipy.stats import linregress

In [16]:
# File to Load 
USyoutube_data_to_load = "output/cleaned_us_data.csv"

# Read Data File and store into Pandas DataFrames
USyoutube_data_to_load_df = pd.read_csv(USyoutube_data_to_load)
USyoutube_data_to_load_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,trending_date_formatted,publish_time_formatted,publish_day,publish_month,publish_year,tag_count
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,...,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,2017-11-14,2017-11-13 17:13:01+00:00,Monday,November,2017,1
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,False,"One year after the presidential election, John...",2017-11-14,2017-11-13 07:30:00+00:00,Monday,November,2017,4
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,...,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,2017-11-14,2017-11-12 19:05:24+00:00,Sunday,November,2017,23
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,...,False,False,False,Today we find out if Link is a Nickelback amat...,2017-11-14,2017-11-13 11:00:04+00:00,Monday,November,2017,27
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,...,False,False,False,I know it's been a while since we did this sho...,2017-11-14,2017-11-12 18:01:41+00:00,Sunday,November,2017,14

In [17]:
USyoutube_data_to_load_df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'trending_date_formatted',
       'publish_time_formatted', 'publish_day', 'publish_month',
       'publish_year', 'tag_count'],
      dtype='object')

In [18]:
(USyoutube_data_to_load_df["category_id"]).unique()

array([22, 24, 23, 28,  1, 25, 17, 10, 15, 27, 26,  2, 19, 20, 29])

In [19]:
assignable_list =[]

with open ("US_category_id.json") as f:
    data = json.load (f)

for item in data["items"]:
    assignable_list.append(item["snippet"]["assignable"])
 
assignable_list

[True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [20]:
id_list =[]

with open ("US_category_id.json") as f:
    data = json.load (f)

for item in data["items"]:
    id_list.append(item["id"])

id_list

['1',
 '2',
 '10',
 '15',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44']

In [21]:
title_list = [] 

with open ("US_category_id.json") as f:
    data = json.load (f)

for item in data["items"]:
    title_list.append(item["snippet"]["title"])

title_list

['Film & Animation',
 'Autos & Vehicles',
 'Music',
 'Pets & Animals',
 'Sports',
 'Short Movies',
 'Travel & Events',
 'Gaming',
 'Videoblogging',
 'People & Blogs',
 'Comedy',
 'Entertainment',
 'News & Politics',
 'Howto & Style',
 'Education',
 'Science & Technology',
 'Nonprofits & Activism',
 'Movies',
 'Anime/Animation',
 'Action/Adventure',
 'Classics',
 'Comedy',
 'Documentary',
 'Drama',
 'Family',
 'Foreign',
 'Horror',
 'Sci-Fi/Fantasy',
 'Thriller',
 'Shorts',
 'Shows',
 'Trailers']

In [22]:
Title_Id_df=pd.DataFrame({"Title": title_list, "Id":id_list, "Assignable":assignable_list})
Title_Id_df

                    Title  Id  Assignable
0        Film & Animation   1        True
1        Autos & Vehicles   2        True
2                   Music  10        True
3          Pets & Animals  15        True
4                  Sports  17        True
5            Short Movies  18       False
6         Travel & Events  19        True
7                  Gaming  20        True
8           Videoblogging  21       False
9          People & Blogs  22        True
10                 Comedy  23        True
11          Entertainment  24        True
12        News & Politics  25        True
13          Howto & Style  26        True
14              Education  27        True
15   Science & Technology  28        True
16  Nonprofits & Activism  29        True
17                 Movies  30       False
18        Anime/Animation  31       False
19       Action/Adventure  32       False
20               Classics  33       False
21                 Comedy  34       False
22            Documentary  35       False
23                  Drama  36       False
24                 Family  37       False
25                Foreign  38       False
26                 Horror  39       False
27         Sci-Fi/Fantasy  40       False
28               Thriller  41       False
29                 Shorts  42       False
30                  Shows  43       False
31               Trailers  44       False

In [23]:
USyoutube_data_to_load_df["category_id_title"] = ''
USyoutube_data_to_load_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,ratings_disabled,video_error_or_removed,description,trending_date_formatted,publish_time_formatted,publish_day,publish_month,publish_year,tag_count,category_id_title
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,...,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,2017-11-14,2017-11-13 17:13:01+00:00,Monday,November,2017,1,
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,"One year after the presidential election, John...",2017-11-14,2017-11-13 07:30:00+00:00,Monday,November,2017,4,
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,...,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,2017-11-14,2017-11-12 19:05:24+00:00,Sunday,November,2017,23,
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,...,False,False,Today we find out if Link is a Nickelback amat...,2017-11-14,2017-11-13 11:00:04+00:00,Monday,November,2017,27,
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,...,False,False,I know it's been a while since we did this sho...,2017-11-14,2017-11-12 18:01:41+00:00,Sunday,November,2017,14,

array([22, 24, 23, 28,  1, 25, 17, 10, 15, 27, 26,  2, 19, 20, 29])

In [28]:
USyoutube_data_to_load_df["category_id"] = USyoutube_data_to_load_df["category_id"].append(USyoutube_data_to_load_df["category_id_title"]
{'22': 'People & Blogs', 
'24': 'Entertainment', 
'23': 'Comedy',
'28': 'Science & Technology', 
'1': 'Film & Animation',
'25': 'News & Politics',
'17': 'Sports',
'10': 'Music',
'15': 'Pets & Animals',
'27': 'Education',
'26': 'Howto & Style',
'2': 'Autos & Vehicles',
'19': 'Travel & Events',
'20': 'Gaming',
'29': 'Nonprofits & Activism',})

SyntaxError: invalid syntax (4272666535.py, line 2)

In [27]:
for category in USyoutube_data_to_load_df["category_id"]:
    if category == 22:
        USyoutube_data_to_load_df["category_id_title"].append("People & Blogs")
        
# USyoutube_data_to_load_df
#     categories_df.loc[index, "category_id title"] = data["items"][0]["snippet"]["title"]

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

In [ ]:
USyoutube_data_to_load_df